import React from "react";

export default function journy() {
  return (
    <div className="  w-11/12 2xl:max-w-[1600px] ml-auto mr-auto my-10 sm:my-20">
<h1 class=" text-base sm:text-2xl 2xl:text-4xl f-f-li captalize text-green tracking-[1px] lg:tracking-[0.22em] text-center ">Privacy Policy</h1>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">Thank you for visiting vmeals.ae The Company, (herein referred to as “We”) appreciates the importance of The Customer’s, (referred herein to as “You/Your”) trust. This Privacy Policy describes the types of personal and non-personal information we collect on the Site, how we use such information and to whom and under what circumstances we may disclose it. By accessing the Site on any computer, mobile phone, tablet, or other device (herein collectively referred to as, “Device”), you agree to the terms of this Privacy Policy. If you do not agree to the policy, please do not use the site.</h2>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">We reserve the right to modify this Privacy Policy at any time. If we decide to change any of the clause in this Privacy Policy, we will post those changes on our Site. We therefore encourage you to periodically review our Privacy Policy to stay informed about how we are using the information we collect.</h2>
    
<h1 class=" text-tiny f-f-b captalize text-green  text-center  md:text-left mt-2 md:mt-7 ">A. Collection of Information</h1>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">You may visit and browse the Sites without providing personally identifiable information about yourself. However, this may limit your ability to receive certain features, products or services from us.</h2>
<h1 class=" text-tiny f-f-b captalize text-green  text-center  md:text-left mt-2 md:mt-7 ">*Personal Information:</h1>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">We collect personal information from you when you submit it to us, including by: (a) registering on the Site; (b) placing an order; (c) signing up for our newsletter; (d) contacting us; or (d) participating in a Site promotion or survey. This information may include, for example, your name, email address, mailing address, billing address, telephone number, date of birth, and credit or debit card information. We collect and store the information provided. We may also ask you to provide other information, such as demographic information, age or about your product preferences and interests.</h2>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">You may also be able to register and log in using your Facebook account. When you use a social media account to log into the Sites, you may also be able to use certain social features on the Sites. For Facebook log in, Facebook will ask your permission to share certain information from your Facebook account with the Site. This may include your first name, last name, gender, profile picture, list of friends, a link to your Facebook profile, interests and other data that is part of your or your friends’ Facebook profile(s). This information is collected by Facebook and is provided to us under the terms of Facebook’s privacy policy. You can control the information that we receive from Facebook using the privacy settings in your Facebook account.</h2>
<h1 class=" text-tiny f-f-b captalize text-green  text-center  md:text-left mt-2 md:mt-7 ">B. Information We Collect Automatically</h1>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">When you visit the Site, we may collect certain non-personal information from you, including your Internet Protocol (IP) address, browser type, operating system, the specific web pages visited during your connection, and the domain name from which you accessed the Site. In addition, we may collect information about your browsing behaviour, such as the date and time you visit the Site, the areas or pages of the Site that you visit, the amount of time you spend viewing the Site, the number of times you return to the Site and other clickstream data. We may also use non-personal information for statistical analysis, research, and other purposes.</h2>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">Like many Web sites, we use “Cookies,” which are data files placed on a Device when it is used to visit the Sites to facilitate site navigation, personalize your experience, and includes tailoring advertisements. Cookies may also be used to associate you with social networking sites like Facebook and Instagram and, if you so choose, enable interaction between your activities on the Sites and your activities on these social networking sites. We, may place cookies or similar files on your Device for security purposes, to facilitate site navigation and to personalize your experience while visiting our Sites (such as allowing us to select which ads or offers are most likely to appeal to you, based on your interests, preferences, location, or demographic information).</h2>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">If you would prefer not to accept cookies, you will be notified with a pop-up in the browser which lets you choose whether or not to accept it; or set your browser to automatically not accept any cookies. However, please be aware that some features and services on our Sites may not work properly because we may not be able to recognize and associate you with your account. In addition, the offers we provide when you visit us may not be as relevant to you or tailored to your interests. We may combine the non-personal information we collect through cookies with other information we have collected from you.</h2>
<h1 class=" text-tiny f-f-b captalize text-green  text-center  md:text-left mt-2 md:mt-7 ">C. Use of Information</h1>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">We may use the information we collect from and about you for any of the following purposes: (a) to fulfil your requests for products; (b) to respond to your inquiries; (c) to review Site usage and operations; (d) to address problems with the Site, our business or our services; (e) to protect the security or integrity of the Site and our business; (f) to monitor the Site for compliance with our Terms of Use and the law; and (g) to contact you with Site updates, newsletters and other informational and promotional materials from us and third party marketing offers from our trusted partners.</h2>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">If you do not wish to receive communications from us about special offers and promotions, you can opt-out of receiving these communications by following the instructions contained in the messages you receive. Even if you opt-out of receiving these messages, we reserve the right to send you certain communications relating to the services we provide, and we may send you service announcements and administrative messages. We do not offer you the opportunity to opt-out of receiving those communications.</h2>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">We may share non–Personal Information, such as aggregate user statistics, demographic information, and Usage Information with third parties, except as provided in this Privacy Policy and Cookie Notice, we will not provide any of your Personal Information to any third parties without your specific consent.</h2>
<h1 class=" text-tiny f-f-b captalize text-green  text-center  md:text-left mt-2 md:mt-7 ">D. Disclosure of Information</h1>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">We may disclose information collected from and about you with other entities FLIP SIDE RESTAURANT AND CAFÉ L.L.C as follows: (1) to perform a business, professional or technical support function for us; (2) to our marketing partners, advertisers or other third parties, who may contact you with their own offers; (3) as necessary if we believe that there has been a violation of the Site Terms of Use or of our rights or the rights of any third party; (4) to respond to legal process (such as a search warrant, subpoena or court order) and provide information to law enforcement agencies or in connection with an investigation on matters related to public safety, as required by law; and (5) in the event that our company or substantially all of its assets are acquired, your personal information may be one of the transferred assets. We may also disclose your personal information with your express consent. We may share aggregate, non-personally identifiable information about Site users with third parties.</h2>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">Please note that if you voluntarily submit any personal information for posting on the Site, such as a review or a blog post, the information becomes publicly available and can be collected and used by others, so you should use care before posting information about yourself online.</h2>
<h1 class=" text-tiny f-f-b captalize text-green  text-center  md:text-left mt-2 md:mt-7 ">E. Access to Your Personal Information</h1>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">You may access your personal information by signing into your account. From there, you can correct or modify your information.</h2>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">If you wish to modify, verify, correct, delete, or update any of your Personal Information collected through the Sites, you may edit your profile preferences or contact us at the above address or e–mail. In accordance with our regular record keeping, we may delete certain records that contain Personal Information you have submitted through the Sites. We are under no obligation to store such Personal Information indefinitely and disclaim any liability arising out of the destruction of such Personal Information. In addition, you should be aware that it is not always possible to completely remove or delete all of your information from our databases without some residual data because of backups and other reasons.</h2>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">We will retain your information (including geo–location data) while your account is active or as needed to provide you services. If you wish to cancel your account or request that we no longer use your information to provide you services please contact us. We will retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements. We do not control certain privacy settings and preferences maintained by our social media partners like Facebook and Instagram. If you wish to make changes to those settings and preferences, you may do so by visiting the settings page of the appropriate social media site.</h2>
<h1 class=" text-tiny f-f-b captalize text-green  text-center  md:text-left mt-2 md:mt-7 ">F. Security</h1>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">We maintain appropriate measures designed to safeguard the information we collect in a secure manner. Even though we follow reasonable procedures to try to protect the information in our possession, no security system is perfect and we cannot guarantee, and you should not expect, that your information will be secure in all circumstances.</h2>

<h1 class=" text-tiny f-f-b captalize text-green  text-center  md:text-left mt-2 md:mt-7 ">G. Interest Based Advertising</h1>
<h2 class=" f-f-r text-black text-tiny 2xl:text-lg mt-2 md:mt-7 leading-[25px] text-center xl:text-left ">We use licenses and third-party advertising companies that use tracking technologies and analytics to serve advertisements across the Internet and evaluate and provide us with information about the use of the Sites and viewing of our content. We do not share Personal Information with these third parties, these companies may collect anonymous information about your visits to the Site and other websites and your interaction with our advertising and other communications. These advertising companies serve ads on our behalf and others on non-affiliated sites, and some of those ads may be personalized, meaning that they are intended to be relevant to you based on information collected about your visits to this site and elsewhere over time. We may use a variety of companies to serve advertisements.

</h2>


    </div>
  );
}
